spring.application.name=recon

# Example for an H2 In-Memory database
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password

# Prevents all jobs from running automatically on startup
spring.batch.job.enabled=false

spring.main.allow-bean-definition-overriding=true
